CarflexWeb/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Carflex.mx.Flota.Services;
using Carflex.mx.Flota.Model;
using Carflex.mx.Catalogo.Services;
using carflex.mx.socio.Services;
using Carflex.mx.Carflexweb.Services;
using Carflex.mx.Carflexweb.Model;

namespace CarflexWeb.Controllers
{
    public class InicioController : Controller
    {
        //
        List<SelectListItem> limarcas = new List<SelectListItem>();
        List<SelectListItem> lilocalidades = new List<SelectListItem>();
        CarflexwebServices cargar = new CarflexwebServices();
        Configuracion oConfiguracion = new Configuracion();

        int SocioId = 1;


        // GET: /Inicio/

        public ActionResult Index()
        {
            limarcas.Add(new SelectListItem { Text = "Todas", Value = "0" });
            lilocalidades.Add(new SelectListItem { Text = "Todas", Value = "0" });
            var localidades = cargar.GetCities(SocioId);
            localidades.ForEach(x => lilocalidades.Add(new SelectListItem { Text = x.Nombre, Value = x.CiudadId.ToString() }));

            List<MarcaVM> lsMarca = new List<MarcaVM>();
            lsMarca = cargar.GetBrands(SocioId);
            foreach (var x in lsMarca)
            {
                limarcas.Add(new SelectListItem
                {
                    Text = x.Nombre,
                    Value = x.MarcaId.ToString(),
                });
            }

            Carflex.mx.Catalogo.Model.FiltroVM oFiltro = new Carflex.mx.Catalogo.Model.FiltroVM();
            Carflex.mx.Catalogo.Model.FiltroVM oFiltro1 = new Carflex.mx.Catalogo.Model.FiltroVM();
            Carflex.mx.Catalogo.Model.FiltroVM oFiltro2 = new Carflex.mx.Catalogo.Model.FiltroVM();
            Carflex.mx.Catalogo.Model.FiltroVM oFiltro3 = new Carflex.mx.Catalogo.Model.FiltroVM();

            Carflex.mx.Catalogo.Model.FiltroVM oFiltroSlider = new Carflex.mx.Catalogo.Model.FiltroVM();
            Carflex.mx.Catalogo.Model.FiltroVM oFiltroFlota = new Carflex.mx.Catalogo.Model.FiltroVM();
            Carflex.mx.Catalogo.Model.FiltroVM oFiltroFlota2 = new Carflex.mx.Catalogo.Model.FiltroVM();
            Carflex.mx.Catalogo.Model.FiltroVM oFiltroFlota3 = new Carflex.mx.Catalogo.Model.FiltroVM();
            Carflex.mx.Catalogo.Model.FiltroVM oFiltroFlota4 = new Carflex.mx.Catalogo.Model.FiltroVM();

            
            //en una pagina solo puede haber una plantilla

            oFiltroSlider.SocioId = SocioId;
            oFiltroSlider.NombrePagina = "home.aspx";
            oFiltroSlider.NombreArea = "Slider";

            oFiltro.SocioId = SocioId;
            oFiltro.NombrePagina = "home.aspx";
            oFiltro.NombreArea = "Publicidad Home";

            oFiltro1.SocioId = SocioId;
            oFiltro1.NombrePagina = "home.aspx";
            oFiltro1.NombreArea = "Publicidad Home 2";

            oFiltro2.SocioId = SocioId;
            oFiltro2.NombrePagina = "home.aspx";
            oFiltro2.NombreArea = "Publicidad Home 3";

            oFiltro3.SocioId = SocioId;
            oFiltro3.NombrePagina = "home.aspx";
            oFiltro3.NombreArea = "Publicidad Home 4";


            oFiltroFlota.SocioId = SocioId;
            oFiltroFlota.NombrePagina = "home.aspx";
            oFiltroFlota.NombreArea = "Home flota 1";


            oFiltroFlota2.SocioId = SocioId;
            oFiltroFlota2.NombrePagina = "home.aspx";
            oFiltroFlota2.NombreArea = "Home flota 2";


            oFiltroFlota3.SocioId = SocioId;
            oFiltroFlota3.NombrePagina = "home.aspx";
            oFiltroFlota3.NombreArea = "Home flota 3";


            oFiltroFlota4.SocioId = SocioId;
            oFiltroFlota4.NombrePagina = "home.aspx";
            oFiltroFlota4.NombreArea = "Home flota 4";

            ViewData["lsFiltro"] = oFiltro;
            ViewData["lsFiltro1"] = oFiltro1;
            ViewData["lsFiltro2"] = oFiltro2;
            ViewData["lsFiltro3"] = oFiltro3;
            ViewData["FiltroSlider"] = oFiltroSlider;
            ViewData["FiltroFlota"] = oFiltroFlota;
            ViewData["FiltroFlota2"] = oFiltroFlota2;
            ViewData["FiltroFlota3"] = oFiltroFlota3;
            ViewData["FiltroFlota4"] = oFiltroFlota4;

            oConfiguracion = cargar.GetConfigurationPriceSlider(1);

            ViewBag.Config = oConfiguracion;
            ViewData["lsmarcas"] = limarcas;
            ViewData["lslocalidades"] = lilocalidades;
            ViewData["lsmodelos"] = "Todas";
            ViewData["mva"] = "";
            ViewData["precioinicial"] = 0;
            ViewData["preciofinal"] = 60000;

            return View();
        }

        public ActionResult CargaCombosByMarca(string id)
        {
            int MarcaId = Convert.ToInt32(id);
            List<string> lsModel = cargar.GetModels(MarcaId);

            if (HttpContext.Request.IsAjaxRequest())
            {
                return Json(lsModel, JsonRequestBehavior.AllowGet);
            }

            return RedirectToAction("Index");
        }

    }
}

CarflexWeb/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Carflex.mx.Flota.Services;
using Carflex.mx.Flota.Model;
using System.Threading.Tasks;
using CarflexWeb.Controllers;
using Carflex.mx.Carflexweb.Services;

namespace CarflexWeb.Controllers
{
    public class VentaController : Controller
    {
        CarflexwebServices cargar = new CarflexwebServices();
        List<AutoWebVM> lsautos = new List<AutoWebVM>();
        List<SelectListItem> limarcas = new List<SelectListItem>();
        List<SelectListItem> lilocalidades = new List<SelectListItem>();
        int SocioId = 1;
        // GET: /Venta/
        public ActionResult Index()
        {
            limarcas.Add(new SelectListItem { Text = "Todas", Value = "0" });
            lilocalidades.Add(new SelectListItem { Text = "Todas", Value = "0" });
            var localidades = cargar.GetCities(SocioId);
            localidades.ForEach(x => lilocalidades.Add(new SelectListItem { Text = x.Nombre, Value = x.CiudadId.ToString() }));
            List<MarcaVM> lsMarca = new List<MarcaVM>();
            lsMarca = cargar.GetBrands(SocioId);
            foreach (var x in lsMarca)
            {
                limarcas.Add(new SelectListItem
                {
                    Text = x.Nombre,
                    Value = x.MarcaId.ToString(),
                });
            }

            ViewData["lsmarcas"] = limarcas;
            ViewData["localidades"] = lilocalidades;
            ViewData["precio"] = 0.0;
            ViewData["mva"] = "";
            lsautos = cargar.GetCars(SocioId, 0, 0, "", "", 0.0, 0.0);
            ViewData["passedArray"] = lsautos;
            return View();
        }


        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            int LocalidadId = -1;
            int MarcaId = -1;
            string Modelo = form["modelos"];
            double PrecioInicial = -1;
            double PrecioFinal = -1;
            string Mva = form["mva"];
            if (form["modelos"] == "Todas")
                Modelo = null;
            try
            {
                LocalidadId = Convert.ToInt32(form["localidades"]);
            }
            catch (FormatException e)
            {
                
            }
            try
            {
                MarcaId = Convert.ToInt32(form["marcas"]);
            }
            catch (FormatException e)
            {
                Console.WriteLine("Combo Marcas no retorna un dígito");
            }
            try
            {
                string preciofinal = form["slider-snap-value-upper1"] == null ? "0" : form["slider-snap-value-upper1"];
                PrecioFinal = double.Parse(preciofinal);
            }
            catch (FormatException e)
            {
                Console.WriteLine("Combo Marcas no retorna un dígito");
            }
            try
            {

                PrecioInicial = double.Parse(form["slider-snap-value-lower1"].ToString());
            }
            catch (FormatException e)
            {
                Console.WriteLine("Combo Marcas no retorna un dígito");
            }

            limarcas.Add(new SelectListItem { Text = "Todas", Value = "0" });
            lilocalidades.Add(new SelectListItem { Text = "Todas", Value = "0" });
            var localidades = cargar.GetCities(SocioId);
            localidades.ForEach(x => lilocalidades.Add(new SelectListItem { Text = x.Nombre, Value = x.CiudadId.ToString() }));
            List<MarcaVM> lsMarca = new List<MarcaVM>();
            lsMarca = cargar.GetBrands(SocioId);
            foreach (var x in lsMarca)
            {
                limarcas.Add(new SelectListItem
                {
                    Text = x.Nombre,
                    Value = x.MarcaId.ToString(),
                });
            }
            lsautos = cargar.GetCars(SocioId, MarcaId, LocalidadId, Modelo, Mva, PrecioInicial, PrecioFinal);
            ViewData["lsmarcas"] = limarcas;
            ViewData["localidades"] = lilocalidades;
            ViewData["precio"] = 0.0;
            ViewData["mva"] = "";
            ViewData["passedArray"] = lsautos;
            // int marcaid = 0;
            // string modelo = "Todas";
            // int localidadid = 0;
            // string mva = "";
            // ViewData["mva"] = mva;
            // double precioInicial =0.0;
            // if (!string.IsNullOrEmpty(form["mva"]))
            // {
            //     mva = (form["mva"]);
            //     ViewData["mva"] = mva;
            // }

            // List<SelectListItem> lilocalidades = new List<SelectListItem>();
            // lilocalidades.Add(new SelectListItem { Text = "Todas", Value = "0" });          
            // if ((form["localidades"]) == "0")
            // {
            //     localidadid = Convert.ToInt32(form["localidades"]);
            //     LocalidadVM locs = new LocalidadVM();
            //     var localidades = cargar.getAllLocations();
            //     foreach (var x in localidades)
            //     {
            //         lilocalidades.Add(new SelectListItem
            //         {
            //             Text = x.Nombre,
            //             Value = x.CiudadId.ToString()
            //         });
            //     }
            //     ViewData["localidades"] = lilocalidades;
            // }
            // else
            // {
            //     localidadid = Convert.ToInt32(form["localidades"]); //un entero mayor que cero
            //     LocalidadVM locs = new LocalidadVM();
            //     var localidades = cargar.getAllLocations();
            //     foreach (var x in localidades)
            //     {
            //         lilocalidades.Add(new SelectListItem
            //         {
            //             Text = x.Nombre,
            //             Value = x.CiudadId.ToString(),
            //             Selected = localidadid == x.CiudadId ? true : false
            //         });
            //     }
            //     ViewData["localidades"] = lilocalidades;
            //     var localidadmostrar = from s in lilocalidades where s.Selected select s.Text;
            //     string localidad2 = localidadmostrar.FirstOrDefault();
            //     ViewData["localidadmostrar"] = localidad2;
            // }

            // List<SelectListItem> limarcas = new List<SelectListItem>();
            // limarcas.Add(new SelectListItem { Text = "Todas", Value = "0" });
            // if ((form["marcas"]) == "0")
            // {
            //     ViewData["marcamostrar"] = null;
            //     marcaid = Convert.ToInt32(form["marcas"]);
            //     BusquedaVM busqueda = new BusquedaVM();
            //     busqueda = cargar.CargaMarcas();
            //     foreach (var x in busqueda.marcas)
            //     {
            //         limarcas.Add(new SelectListItem
            //         {
            //             Text = x.Nombre,
            //             Value = x.MarcaId.ToString()
            //         });
            //     }
            //     ViewData["lsmarcas"] = limarcas;
            //     List<SelectListItem> limodelos = new List<SelectListItem>();
            //     limodelos.Add(new SelectListItem { Text = "Todas", Value = "Todas" });
            //     ViewData["lsmodelos"] = limodelos;
            // }
            // else
            // {
            //     ViewData["marcamostrar"] = (form["marcas"]);
            //     marcaid = Convert.ToInt32(form["marcas"]); //recibe un entero mayor que cero
            //     BusquedaVM busqueda = new BusquedaVM();
            //     busqueda = cargar.CargaMarcas();
            //     foreach (var x in busqueda.marcas)
            //     {
            //         limarcas.Add(new SelectListItem
            //         {
            //             Text = x.Nombre,
            //             Value = x.MarcaId.ToString(),
            //             Selected = marcaid == x.MarcaId ? true : false
            //         });
            //     }
            //     ViewData["lsmarcas"] = limarcas;
            //     string marcamostrar = busqueda.marcas.Where(m => m.MarcaId.Equals(marcaid)).Select(d => d.Nombre).FirstOrDefault();
            //     ViewData["marcamostrar"] = marcamostrar;

            //     List<SelectListItem> limodelos = new List<SelectListItem>();
            //     limodelos.Add(new SelectListItem { Text = "Todas", Value = "Todas" });
            //     if ((form["modelos"]) != "Todas")
            //     {
            //         modelo = (form["modelos"]);
            //         var lsmarca = cargar.ModelosByMarcaId(marcaid);

            //         foreach (var x in lsmarca.modelos)
            //         {
            //             limodelos.Add(new SelectListItem
            //             {
            //                 Text = x.Modelo,
            //                 Value = x.Modelo,
            //                 Selected = modelo == x.Modelo ? true : false
            //             });
            //         }

            //         ViewData["modelomostrar"] = modelo;
            //         ViewData["lsmodelos"] = limodelos;
            //     }
            //     else {
            //         modelo = (form["modelos"]);//debe ser "Todas"
            //     var lsmarca = cargar.ModelosByMarcaId(marcaid);
            //     foreach (var x in lsmarca.modelos)
            //     {
            //         limodelos.Add(new SelectListItem
            //         {
            //             Text = x.Modelo,
            //             Value = x.Modelo
            //         });
            //     }

CarflexWeb/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/Images/favicon.png" rel="shortcut icon" type="image/x-icon" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <!--[if lt IE 8]>
    <div style=' clear: both; text-align:center; position: relative;'>
        <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode">
            <img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." />
        </a>
    </div>
    <![endif]-->
    <!--[if lt IE 9]>
        <script src="Scripts/html5shiv.min.js"></script>
        <script src="Scripts/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div>
        <!--..::::::::::::::::::::================  INICIO HEADER  ================::::::::::::::::::::..-->
        <header>
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-3 col-header-01">
                        <div class="logo">
                            @Html.Raw(@Html.ActionLink("[replacetext]", "Index", "Inicio").ToHtmlString().Replace("[replacetext]", "<img src=\"../Images/logo-CarFlex.jpg\" />"))
                        </div>
                    </div>
                    <div class="col-md-9 col-sm-9">
                        <div class="row">
                            <div class="col-md-7 col-sm-12 col-header-02">
                                <form class="navbar-form navbar-right" role="search">
                                    <div class="input-group">
                                        @Html.TextBox("Nombre", "", new { @class = "form-control", placeholder = "Ingrese su busqueda" })
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" type="button">Buscar</button>
                                        </span>
                                    </div>
                                </form>
                            </div>
                            <div class="col-md-2 col-sm-12 col-header-03 text-center">
                                <a class="btn btn-block" href="#" role="button">Iniciar sesión<span class="glyphicon glyphicon-user"></span></a>
                            </div>
                            <div class="col-md-1 col-sm-12 col-header-03 text-left">
                                <a class="btn btn-block btn-shopping-cart popbtn">2<span class="glyphicon glyphicon-shopping-cart"></span></a>
                            </div>
                            <div class="col-md-2 col-sm-12 col-header-04 text-right">
                                <b>01-800 - CARFLEX</b>
                                <br>
                                <small>01 800 - 2273539</small>
                            </div>
                        </div>
                    </div>
                    <!-- VENTANA DESPLEGABLE DEL CARRITO DE COMPRA -->
                    <div id="popover" class="popover">
                        <table class="table autos-similares">
                            <tbody>
                                <tr>
                                    <td class="col-md-4 text-left">
                                        <a href="car-Cardex.html"><img src="images/thumbnail/img-thumbnail-01.jpg" class="img-thumbnail" alt="Image 1"></a>
                                    </td>
                                    <td class="col-md-6 margen-td">
                                        <h6><a href="car-Cardex.html">Chevrolet Chevy 2012</a></h6>
                                        <p>$ 134,000 MXN</p>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="col-md-4">
                                        <a href="car-Cardex.html">
                                            <img src="images/thumbnail/img-thumbnail-02.jpg" class="img-thumbnail" alt="Image 1">
                                        </a>
                                    </td>
                                    <td class="col-md-6 margen-td">
                                        <h6><a href="car-Cardex.html">Chevrolet Chevy 2012</a></h6>
                                        <p>$ 134,000 MXN</p>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="col-md-4">
                                        <a href="car-Cardex.html">
                                            <img src="images/thumbnail/img-thumbnail-03.jpg" class="img-thumbnail" alt="Image 1">
                                        </a>
                                    </td>
                                    <td class="col-md-6 margen-td">
                                        <h6><a href="car-Cardex.html">Chevrolet Chevy 2012</a></h6>
                                        <p>$ 134,000 MXN</p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <hr>
                        <a href="" class="btn btn-block">Pedir Cotización</a>
                    </div>
                </div>
            </div>
            <nav role="navigation" class="navbar navbar-default">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div id="navbarCollapse" class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="@ViewBag.Active1">@Html.ActionLink("INICIO", "Index", "Inicio")</li>
                            <li class="@ViewBag.Active2">@Html.ActionLink("VENTA", "Index", "Venta")</li>
                            <li class="@ViewBag.Active3">@Html.ActionLink("RENTA", "Index", "Renta")</li>
                            <li class="@ViewBag.Active4">@Html.ActionLink("FINANCIAMIENTO", "Index", "Financiamiento")</li>
                            <li class="@ViewBag.Active5">@Html.ActionLink("PROGRAMAS Y SERVICIOS", "Index", "ProgramasServices")</li>
                            <li class="@ViewBag.Active6">@Html.ActionLink("PROMOCIONES", "Index", "Promociones")</li>
                            <li class="@ViewBag.Active7">@Html.ActionLink("OFICINAS", "Index", "Oficinas")</li>
                        </ul>

                        <ul class="nav navbar-nav navbar-right">
                            <li class="hidden-xs hidden-sm barra-Vertical"><span>|</span></li>
                            <li class="@ViewBag.Active8">@Html.ActionLink("CONTACTO", "Index", "Contacto")</li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <!--..::::::::::::::::::::================ FIN DE HEADER ================::::::::::::::::::::..-->
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <!--..::::::::::::::::::::================ FOOTER HOME ================::::::::::::::::::::..-->
        <footer id="footerHome">
            <div class="container" style="width: 100%;">
                <hr class="hr" />
                <div class="row margenFooter">
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="footer-col-01">
                            <h4>Por ciudades</h4>
                            <ul class="list-group">
                                <li class="list-group-item"><a href="">Cancún</a></li>
                                <li class="list-group-item"><a href="">Ciudad de México</a></li>
                                <li class="list-group-item"><a href="">Guadalajara</a></li>
                                <li class="list-group-item"><a href="">León</a></li>
                                <li class="list-group-item"><a href="">Mérida</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="footer-col-01">
                            <h4>Productos y Servicios</h4>
                            <ul class="list-group">
                                <li class="list-group-item"><a href="">Garantía</a></li>
                                <li class="list-group-item"><a href="">Financiamiento</a></li>
                                <li class="list-group-item"><a href="">Autos substituto</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="clearfix visible-sm visible-xs"></div>
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="footer-col-01">
                            <h4>Por tamaño</h4>
                            <div style="float:left">
                                <ul class="list-group">
                                    <li class="list-group-item"><a href="">Económico</a></li>
                                    <li class="list-group-item"><a href="">Compacto</a></li>
                                    <li class="list-group-item"><a href="">Intermedio</a></li>
                                    <li class="list-group-item"><a href="">Grande</a></li>
                                </ul>
                            </div>
                            <div style="float:left">
                                <ul class="list-group">
                                    <li class="list-group-item"><a href="">Jeep Wrangler</a></li>
                                    <li class="list-group-item"><a href="">Lujo</a></li>
                                    <li class="list-group-item"><a href="">4x4</a></li>
                                    <li class="list-group-item"><a href="">Van</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-6">
                        <div class="footer-col-01">
                            <div class="list-group">
                                <a href="#" class="list-group-item"><span class="fa fa-phone"></span> 01 (800) 227 3539</a>
                                <a href="#" class="list-group-item"><span class="fa fa-twitter"></span> Síguenos en Twitter</a>
                                <a href="#" class="list-group-item"><span class="fa fa-facebook"></span> Síguenos en Facebook</a>
                                <a href="#" class="list-group-item"><span class="fa fa-envelope"></span> Contacto</a>
                            </div>
                        </div>
                    </div>
                </div>
                <hr class="hr" />
                <div class="row margenFooter">
                    <div class="col-lg-12">
                        <p style="margin-left:10px;">@DateTime.Now.Year &copy; Comercial Ariete, S.A. de C.V. Todos los derechos reservados.</p>
                    </div>
                </div>
            </div>
        </footer>
        <!--..::::::::::::::::::::================ FIN DE FOOTER HOME ================::::::::::::::::::::..-->
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/scriptspage")
        <script src="@Url.Content("~/scripts/jquery.nouislider.js")"></script>
        @RenderSection("scripts", required: false)
        <script type="text/javascript">
            $(document).ready(function () {
                $('#tooltipModelo').tooltip();
                $('#tooltipAnio').tooltip();
                $('#tooltipCiudad').tooltip();
                $('#tooltipMva').tooltip();
                $('#tooltipPrecio').tooltip();
                $('.tooltip-examples a').tooltip({
                    placement: 'top'
                });
                $('.tooltip-titles h5').tooltip({
                    placement: 'top'
                });
                $('.tooltip-body a').tooltip({
                    placement: 'top'
                });
            });
        </script>
    </div>
</body>
</html>